name: 🐛 Bug Report
description: Help improve Axelar by reporting bugs you encounter.
title: "[BUG] <brief description>"
labels: ["🛠 bug", "🚦 triage"]
body:
  - type: markdown
    attributes:
      value: "Thank you for contributing to Axelar's improvement by reporting a bug. Please provide detailed information below to help us effectively address the issue."

  - type: checkboxes
    id: duplicates
    attributes:
      label: Duplicate Check
      description: "Ensure this bug has not been reported previously to help streamline our response."
      options:
        - label: "I have searched both 'open' and 'closed' issues to confirm this is a unique bug report."
          required: true

  - type: input
    attributes:
      label: Bug Location
      description: "Identify where you encountered the bug (e.g., Interchain Token Service, Axelar Examples, AxelarJS SDK)."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Bug Description
      description: "Provide a comprehensive description of the bug. Include relevant details and any specific scenarios or contexts."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: "List the steps to reproduce the bug. Numbered steps are preferred for clarity."
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "Describe what you anticipated happening when performing the steps above."
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: "Explain what actually occurred. Include any error messages or unusual behavior."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Supporting Screenshots and Logs
      description: "If possible, add screenshots or logs to aid in understanding the issue."
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: "Rate the severity of the bug (Optional)."
      options:
        - "Critical - System crash, loss of data, severe memory leak."
        - "High - Major functionality broken, greatly affecting user experience."
        - "Medium - Minor functionality broken, workaround possible."
        - "Low - Minor issue, does not significantly impact overall experience."
    validations:
      required: false

  - type: dropdown
    id: assignee
    attributes:
      label: Willingness to Contribute
      description: "Would you like to contribute to fixing this issue?"
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false

  - type: markdown
    attributes:
      value: "🔗 [Join our Discord community](https://discord.com/invite/axelar) for further discussions or support."
