name: 📚 Documentation
description: Suggest improvements to Axelar's documentation.
title: "[DOCS] <brief description>"
labels: ["📄 docs", "🚦 triage"]
body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Has this documentation issue been raised before?
      description: Increase the chances of your issue being accepted by making sure it has not been raised before.
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: input
    attributes:
      label: Specify the documentation section
      description: Please indicate the specific part of the documentation this relates to (e.g., API Guide, Installation Process).
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Describe the Improvement
      description: A clear description of what you think could be improved. Please be as specific as possible.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for Improvement
      description: Explain why you think this improvement is needed. How does it add value?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord community for more discussions on documentation [here](https://discord.com/invite/axelar)
