name: ✨ Feature Request
description: Suggest a new feature for Axelar.
title: "[FEATURE] <brief description>"
labels: ["💡 feature"]
body:
  - type: checkboxes
    id: duplicates
    attributes:
      label: Has this feature been requested before?
      description: Ensure your feature is unique to get better attention.
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: input
    attributes:
      label: Feature Summary
      description: A brief title or summary of the feature you're proposing.
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature. Include any potential benefits, use cases, or problems it solves.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context and Justification
      description: Why is this feature important? Provide any relevant context that justifies the need for this feature.
    validations:
      required: true
  - type: dropdown
    id: interested
    attributes:
      label: Interested in implementing?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        We appreciate your ideas! Join our community on Discord [here](https://discord.com/invite/axelar)