name: 💬 General Feedback
description: Provide general feedback or suggestions for Axelar.
title: "[FEEDBACK] <brief description>"
labels: ["🗣️ feedback"]
body:
  - type: input
    attributes:
      label: Feedback Category
      description: Please categorize your feedback (e.g., User Experience, Technical Issues, General Suggestions).
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Feedback Details
      description: Describe your feedback in detail. Please provide specific examples or scenarios if applicable.
    validations:
      required: true
  - type: input
    attributes:
      label: Impact
      description: What impact does this have on your experience or use of Axelar? (Optional)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Your feedback is valuable to us. For further discussions, join our Discord [here](https://discord.com/invite/axelar)